In [6]:
import torch
import wandb
import gym
import pybullet_envs

In [7]:
env_name="InvertedPendulumBulletEnv-v0"
env = gym.make(env_name)

/Users/MartinShin/.conda/envs/donkey/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [8]:
env.observation_space

Box(-inf, inf, (5,), float32)

In [9]:
env.observation_space.shape

(5,)

In [10]:
env.action_space

Box(-1.0, 1.0, (1,), float32)

In [11]:
env.action_space.shape[0]

1

In [13]:
dir(env)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_elapsed_steps',
 '_max_episode_steps',
 'action_space',
 'class_name',
 'close',
 'compute_reward',
 'env',
 'metadata',
 'observation_space',
 'render',
 'reset',
 'reward_range',
 'seed',
 'spec',
 'step',
 'unwrapped']

In [15]:
env.observation_space

In [1]:
import numpy as np
obs = np.asarray([-0.81701329, -1.31633152,  0.97950409, -0.20142429, -0.35504759])
action = np.asarray([0.37204853])


In [4]:
torch.from_numpy(obs)

tensor([-0.8170, -1.3163,  0.9795, -0.2014, -0.3550], dtype=torch.float64)

In [5]:
torch.from_numpy(action)

tensor([0.3720], dtype=torch.float64)

In [6]:
import torch
torch.cat([torch.from_numpy(obs), torch.from_numpy(action)], dim=0)

tensor([-0.8170, -1.3163,  0.9795, -0.2014, -0.3550,  0.3720],
       dtype=torch.float64)

In [7]:
torch.cat([obs, action], dim=0)

TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray